input_source: "assets/test_video.MOV"
object_images:
  - "assets/air_conditioner.png"
  
object_names:
  - "Air Conditioner"
feature_detector: "sift"  # Options: sift, surf, orb, template
matcher: "flann"  # Options: flann, brute_force
sampling_rate: 60
match_ratio: 0.7
change_threshold: 0.5
min_matches: 10
show_matches: true